/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedServerImport } from './routes/_authed/server'
import { Route as AuthedClientOnlyImport } from './routes/_authed/client-only'
import { Route as AuthedClientOnlyIndexImport } from './routes/_authed/client-only.index'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedServerRoute = AuthedServerImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedClientOnlyRoute = AuthedClientOnlyImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedClientOnlyIndexRoute = AuthedClientOnlyIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedClientOnlyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authed/client-only': {
      id: '/_authed/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AuthedClientOnlyImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/server': {
      id: '/_authed/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthedServerImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/client-only/': {
      id: '/_authed/client-only/'
      path: '/'
      fullPath: '/client-only/'
      preLoaderRoute: typeof AuthedClientOnlyIndexImport
      parentRoute: typeof AuthedClientOnlyImport
    }
  }
}

// Create and export the route tree

interface AuthedClientOnlyRouteChildren {
  AuthedClientOnlyIndexRoute: typeof AuthedClientOnlyIndexRoute
}

const AuthedClientOnlyRouteChildren: AuthedClientOnlyRouteChildren = {
  AuthedClientOnlyIndexRoute: AuthedClientOnlyIndexRoute,
}

const AuthedClientOnlyRouteWithChildren =
  AuthedClientOnlyRoute._addFileChildren(AuthedClientOnlyRouteChildren)

interface AuthedRouteChildren {
  AuthedClientOnlyRoute: typeof AuthedClientOnlyRouteWithChildren
  AuthedServerRoute: typeof AuthedServerRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientOnlyRoute: AuthedClientOnlyRouteWithChildren,
  AuthedServerRoute: AuthedServerRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client-only': typeof AuthedClientOnlyRouteWithChildren
  '/server': typeof AuthedServerRoute
  '/client-only/': typeof AuthedClientOnlyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/server': typeof AuthedServerRoute
  '/client-only': typeof AuthedClientOnlyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/client-only': typeof AuthedClientOnlyRouteWithChildren
  '/_authed/server': typeof AuthedServerRoute
  '/_authed/client-only/': typeof AuthedClientOnlyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/client-only'
    | '/server'
    | '/client-only/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/sign-in' | '/sign-up' | '/server' | '/client-only'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/client-only'
    | '/_authed/server'
    | '/_authed/client-only/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/client-only",
        "/_authed/server"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/_authed/client-only": {
      "filePath": "_authed/client-only.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/client-only/"
      ]
    },
    "/_authed/server": {
      "filePath": "_authed/server.tsx",
      "parent": "/_authed"
    },
    "/_authed/client-only/": {
      "filePath": "_authed/client-only.index.tsx",
      "parent": "/_authed/client-only"
    }
  }
}
ROUTE_MANIFEST_END */
